name: Docker Build & Push
on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action
      - uses: aws-actions/amazon-ecr-login@v2
        with:
          region: eu-central-1
      - name: Build & push
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t 123456789012.dkr.ecr.eu-central-1.amazonaws.com/vg:latest \
            --push .
