name: Generate Station Map

on:
  push:
    branches: [ master ]
    paths:
      - 'src/dwd_opendata/__init__.py'
      - '.github/workflows/generate-station-map.yml'
  workflow_dispatch:  # Allow manual triggering
  schedule:
    # Run monthly to keep the map up-to-date with DWD data
    - cron: '0 0 1 * *'

jobs:
  generate-map:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install system dependencies for cartopy
      run: |
        sudo apt-get update
        sudo apt-get install -y libgeos-dev libproj-dev

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Generate station map
      run: |
        uv run python - <<'EOF'
        import dwd_opendata as dwd
        from datetime import datetime
        import matplotlib
        matplotlib.use('Agg')  # Non-interactive backend
        import matplotlib.pyplot as plt

        start = datetime(1980, 1, 1)
        end = datetime(2016, 12, 31)
        variables = ("wind", "air_temperature", "sun", "precipitation")

        print("Generating station map...")
        fig, ax = dwd.map_stations(
            variables,
            lon_min=7,
            lat_min=47.4,
            lon_max=12.0,
            lat_max=49.0,
            start=start,
            end=end,
        )

        # Save to images directory
        import os
        os.makedirs("images", exist_ok=True)
        fig.savefig("images/station_map.png", dpi=150, bbox_inches='tight')
        print("Station map saved to images/station_map.png")
        EOF

    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add images/station_map.png
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update station map [skip ci]"
          git push
        fi
